### ISSUE TITLE
inference速度

### ISSUE THREAD

**Issue by 2020zyc** [THUNLP-MT/THUMT#59]
你好，我使用你们的线上demo测试inference速度，感觉速度挺快的；
请问有对inference做另外的处理来提升速度吗，比如量化或者剪枝之类的？还是就只用thumt里面实现的transformer或者其他模型？

**Comment by 2020zyc** [comment]
我用T2T的，大致100个字的解码就要1.5s。能否指导一下如何提升速度，多谢

**Comment by 2020zyc** [comment]
@Glaceon31 Zhang   @thudcsly 打扰了，求指导。。。

**Comment by Glaceon31** [comment]
你好，我们没有对inference做特殊的处理。demo的inference速度快是因为使用的GPU。

**Comment by minicheshire** [comment]
你好，确实如@Glaceon31 所说，GPU的加速的解码会快很多。如果条件允许，建议使用可相互通信的多GPU进行解码。

**Comment by 2020zyc** [comment]
非常感谢两位。

**Comment by Felixgithub2017** [comment]
> 你好，我们没有对inference做特殊的处理。demo的inference速度快是因为使用的GPU。

Hi Glaceon31, nice to see u here. I've trained a transformer model using your code, thanks, it is really useful. Based on your instructions, I wrote some script to build a translation pipeline, however it is not graceful, so I hope you could provide some help or code examples on how to deploy the model, thanks in advance!
The followings are my code, which can take in some text string and output translated string, it is not in a graceful way.
Translating a short text may take around 20 seconds, including the model loading time.
Is there a way to load the model once and then do as many translations as I wish?
I hope to provide the bpe-processed text (not a text file) directly to the model and get also text out, so that I can build a web api. I tried to restructure your code but I found it is not easy. So could you offer some suggestions?

The followings are my code:

import os
from nltk import tokenize

def translate_text(inputtext):
    inputtext = inputtext.strip()
    newlines = tokenize.sent_tokenize(inputtext)
    with open('to_be_translated.en', "w") as fw:
        fw.writelines(newlines)
    bashCommand = "./apply_bpe_and_translate.sh"
    os.system(bashCommand)
    with open('to_be_translated.32k.en.trans', "r") as fr:
        lines = fr.readlines()
        return " ".join(lines)

The followings are content of the apply_bpe_and_translate.sh script:
# apply bpe
python subword-nmt/apply_bpe.py --vocabulary vocab32k.en --vocabulary-threshold 1 -c bpe32k < to_be_translated.en > to_be_translated.32k.en

# translate
python translator.py --models transformer --input to_be_translated.32k.en --output to_be_translated.32k.en.trans --vocabulary vocab.32k.en.txt vocab.32k.zh.txt --checkpoints train/eval --parameters=device_list=[0,1]

**Comment by Glaceon31** [comment]
@Felixgithub2017 We recommend using a web service such as Flask to wrap the translator. You can reconstruct translator.py to the following code structure:

`import ...`

`[Build the decoding graph, load the model, etc.]`
`[Initialize your tokenization tool(s)]`

`@app.route('/your_url')`
`def decoding(***):`
&ensp;&ensp;`    [tokenize here]`
&ensp;&ensp;`    [do the translation]`

`if __name__ == "__main__":`
&ensp;&ensp;`    [run Flask app here]`

**Comment by Felixgithub2017** [comment]
> @Felixgithub2017 We recommend using a web service such as Flask to wrap the translator. You can reconstruct translator.py to the following code structure:
> 
> `import ...`
> 
> `[Build the decoding graph, load the model, etc.]`
> `[Initialize your tokenization tool(s)]`
> 
> `@app.route('/your_url')`
> `def decoding(***):`
>   ` [tokenize here]`
>   ` [do the translation]`
> 
> `if __name__ == "__main__":`
>   ` [run Flask app here]`

Thank you Glaceon31. I modified the "translator.py" file and wrote a pipeline.
One more question, do I need to load the model every time when I need to do a translation?
I tested and found that no matter the length of the text to be translated, the minimum time needed is always more than 20 seconds, is this normal? 
I have two Titan RTX, 48Gb ram, and I used them all by specifying the device list parameter.

**Comment by Glaceon31** [comment]
@Felixgithub2017 You don't need to load the model every time. If the translation service is successfully initialized, the model will be kept in GPU memory. The key is to load the model on **initialization** but not on **translation**.

**Comment by Felixgithub2017** [comment]
> @Felixgithub2017 You don't need to load the model every time. If the translation service is successfully initialized, the model will be kept in GPU memory. The key is to load the model on **initialization** but not on **translation**.

Hi Glaceon31, thank you. I rewrote my code and the followings are test results: the time needed is greatly reduced, is this fast enough?
![image](https://user-images.githubusercontent.com/26135691/62602023-4db2c200-b925-11e9-867e-df0673a7f332.png)

**Comment by Glaceon31** [comment]
Hard to say. You can test on GPU or translate a very short sentence. The time cost should be less than 1 second.
